export {About} from "./About"
export {Home} from "./Home"
export {CarPaintings} from "./CarPaintings"
export {CarTinsmiths} from "./CarTinsmiths"
export {WebDevelopments} from "./WebDevelopments"
export {Project} from "./Project"
export {ContactUs} from "./ContactUs"
export {PageNotFound} from "./PageNotFound"
